config/routes.rb
Rails.application.routes.draw do

   

  
resources :loan_detail 
root 'loan_detail#index'

end

app/models/loan_detail.rb
require 'multi_parameter_attributes.rb'
class LoanDetail
  include Mongoid::Document
  field :loan_amount, type: Float
  field :rate_of_interest, type: Float
  field :tenure, type: Integer
  field :pre_payment, type: Float
  field :one_time_payment, type: Float, default: 0
  field :monthly_payment, type: Float, default: 0
  field :yearly_payment, type: Float, default: 0
  field :set_date_one_time_payment, type: DateTime, default: Time.now
  field :set_date_yearly_payment, type: DateTime, default: Time.now
  validates :loan_amount, :presence => true, :numericality => true
  validates :rate_of_interest, :presence => true, :numericality => true
  validates :tenure, :presence => true, :numericality => true, length: { minimum: 1, maximum: 2 }
  validates :one_time_payment, :numericality => true
  validates :monthly_payment, :numericality => true
  validates :yearly_payment, :numericality => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/loan_detail_controller.rb
require 'amortization.rb'
class LoanDetailController < ApplicationController
  def index
    @loanDetails = LoanDetail.all
  end

  def show
  	@loanDetail = LoanDetail.find(params[:id])
  	@payment_details = Amortization.calculate(@loanDetail)
  end

  def new
  	@loanDetail = LoanDetail.new
  end

  def create
  	@loanDetail = LoanDetail.new(loan_detail_params)
  	if @loanDetail.save
  	  redirect_to @loanDetail
    else
      render 'new'
    end
  end

  def edit
    @loanDetail = LoanDetail.find(params[:id])
  end

  def update
    @loanDetail = LoanDetail.find(params[:id])
   
    if @loanDetail.update(loan_detail_params)
      redirect_to @loanDetail
    else
      render 'edit'
    end
  end

  def destroy
    @loanDetail = LoanDetail.find(params[:id])
    @loanDetail.destroy
    redirect_to loan_detail_index_path
  end

  private 
  def loan_detail_params
  	params.require(:loanDetail).permit(:loan_amount, :tenure, :rate_of_interest, :one_time_payment, :set_date_one_time_payment, :monthly_payment, :yearly_payment, :set_date_yearly_payment)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/loan_details_helper.rb
module LoanDetailsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Amortization</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/redmond/jquery-ui.css", "application" %>
<%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js", "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js", "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/loan_detail/edit.html.erb
<h1>Editing previous calculation</h1>
 
<%= form_for :loanDetail, url: loan_detail_path(@loanDetail), method: :patch do |f| %>
 
  <% if @loanDetail.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@loanDetail.errors.count, "error") %> prohibited
        this loan details from being saved:
      </h2>
      <ul>
        <% @loanDetail.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :Loan_Amount %><br>
    <%= f.text_field :loan_amount %>
  </p>
 
  <p>
    <%= f.label :Tenure %><br>
    <%= f.text_field :tenure %>
  </p>

  <p>
    <%= f.label :Rate_of_interest %><br>
    <%= f.text_field :rate_of_interest %>
  </p>

<h3>Extra Payments</h3>

  <p>
    <%= f.label :monthly_payment %><br>
    <%= f.text_field :monthly_payment %>
  </p>

  <p>
    <%= f.label :one_time_payment %><br>
    <%= f.text_field :one_time_payment %>
    <%= f.date_select :set_date_one_time_payment %>
  </p>

  <p>
    <%= f.label :yearly_payment %><br>
    <%= f.text_field :yearly_payment %>
    <%= f.date_select :set_date_yearly_payment %>
  </p>

  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', loan_detail_index_path %>

app/views/loan_detail/index.html.erb
<h1>List of previous inputs</h1>
 <%= link_to 'New Calculation', new_loan_detail_path %>
 <br>
<table>
  <tr>
    <th style="padding-left: 10px">Loan amount</th>
    <th style="padding-left: 10px">Tenure</th>
    <th style="padding-left: 10px">Rate of interest</th>
    <th style="padding-left: 10px">One time payment</th>
    <th style="padding-left: 10px">Monthly payment</th>
    <th style="padding-left: 10px">Yearly payment</th>
  </tr>
 
  <% @loanDetails.each do |loanDetail| %>
   
    <tr>
      <td style="padding-left: 10px"><%= loanDetail.loan_amount %></td>
      <td style="padding-left: 10px"><%= loanDetail.tenure %></td>
      <td style="padding-left: 10px"><%= loanDetail.rate_of_interest %></td>
      <td style="padding-left: 10px"><%= loanDetail.one_time_payment %></td>
      <td style="padding-left: 30px"><%= loanDetail.monthly_payment %></td>
      <td style="padding-left: 30px"><%= loanDetail.yearly_payment %></td>
      <td style="padding-left: 30px"><%= link_to 'Show', loan_detail_path(loanDetail) %></td>
      <td style="padding-left: 10px"><%= link_to 'Edit', edit_loan_detail_path(loanDetail) %></td>
      <td style="padding-left: 10px"><%= link_to 'Destroy', loan_detail_path(loanDetail),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/loan_detail/new.html.erb
<%= form_for :loanDetail, url: loan_detail_index_path do  |f| %>
 
<h1>New Calculation</h1>
  <% if @loanDetail.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@loanDetail.errors.count, "error") %> prohibited
        this loan details from being saved:
      </h2>
      <ul>
        <% @loanDetail.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :Loan_Amount %><br>
    <%= f.text_field :loan_amount %>
  </p>
 
  <p>
    <%= f.label :Tenure %><br>
    <%= f.text_field :tenure %>
  </p>

  <p>
    <%= f.label :Rate_of_interest %><br>
    <%= f.text_field :rate_of_interest %>
  </p>

<h3>Extra Payments</h3>

  <p>
    <%= f.label :monthly_payment %><br>
    <%= f.text_field :monthly_payment %>
  </p>

  <p>
    <%= f.label :one_time_payment %><br>
    <%= f.text_field :one_time_payment %>
    <%= f.date_select :set_date_one_time_payment %>
  </p>

  <p>
    <%= f.label :yearly_payment %><br>
    <%= f.text_field :yearly_payment %>
    <%= f.date_select :set_date_yearly_payment %>
  </p>

  <p>
    <%= f.submit %>
  </p>
 
<% end %>

<%= link_to 'Back', loan_detail_index_path %>

app/views/loan_detail/show.html.erb
<%= link_to 'Back', loan_detail_index_path %>

<table cellpadding="10">
  <tr>
    <th>Total no of Months</th>
    <th>Month of emi</th>
    <th>Emi</th>
    <th>Opening Amount</th>
    <th>Monthly Interest Amount</th>
    <th>Total Interest Amount</th>
    <th>Principal Amount</th>
    <th>Closing Amount</th>
  </tr>
  <% @payment_details.each do |payment_detail| %>
   <tr>
      <td><%= payment_detail['number_of_months'] %></td>
      <td><%= payment_detail['month_of_emi'] %></td>
      <td><%= payment_detail['emi'].round(2) %></td>
      <td><%= payment_detail['loan_amount'].round(2) %></td>
      <td><%= payment_detail['monthly_interest_paid'].round(2)%></td>
      <td><%= payment_detail['total_interest_paid'].round(2) %></td>
      <td><%= payment_detail['principal_paid'].round(2) %></td>
      <td><%= payment_detail['new_balance'].round(2) %></td>
    </tr>
  <% end %>
</table>
 

  